name: Deploy to GitHub Pages

on:
  push:
    branches: ['master', 'main']
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          npm install

      - name: Build project
        run: |
          echo "Building project..."
          npm run build
          echo "Build completed"
          echo "Files in dist directory:"
          ls -la dist

      - name: Create necessary files
        run: |
          touch dist/.nojekyll
          echo "Created .nojekyll file"

      # This is a backup manual deployment strategy that should work even if the action fails
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
